apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    name: in-cluster
    namespace: testing-dev
  source:
    path: .
    repoURL: https://github.com/nharvey-octopus/gitops-testing.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
